name: Weekly boardsmemory Sync

on:
  schedule:
    - cron: "0 18 * * 1"  # 매주 월요일 오전 3시 (UTC 기준 → 한국 시간으로 월요일 정오)
  workflow_dispatch:  # 수동 실행도 가능하게 유지

jobs:
  sync-boardsmemory:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render API to sync-BoardsMemory
        run: |
          curl -X POST https://pc-site-backend.onrender.com/api/sync-boards-memory
